spring:
  datasource:
    url: jdbc:mysql://43.139.44.104:3306/weibo_sign?useSSL=false&serverTimezone=UTC
    username: root
    password: Ajar970122.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  mail:
    host: smtp.qq.com
    port: 587
    username: your@qq.com
    password: your-auth-code
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.ssl.protocols: TLSv1.2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

weibo:
  sign:
    cron: "0 0 8 * * ?" # 默认每天8点执行
  notify:
    template:
      email: |
        微博签到结果通知
        ==============
        账号：${username}
        成功签到：${count}个超话
        详情：${details}
      serverchan: |
        【${username}】微博签到完成
        已签超话：${count}个
        列表：${details}